wildfly-security/wildfly-elytron-tool

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
resolves: 
#12 enhance help messages
- https://issues.jboss.org/browse/WFLY-8191
#13 interactive prompt for password and secret attributes 
- https://issues.jboss.org/browse/JBEAP-9016
- https://issues.jboss.org/browse/JBEAP-9018
#14 do not accept invalid options passed to commands
- https://issues.jboss.org/browse/JBEAP-9033
> compound PR - see commits and comments

- pom.xml
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/test/java/org/wildfly/security/tool/MaskCommandTest.java
With changes related to https://issues.jboss.org/browse/ELY-1013 the mask command has to produce proper output too.
> Resolves #21: mask comand has to be compatible with PicketBox PBE functions

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1056
JBEAP: https://issues.jboss.org/browse/JBEAP-9934
> [ELY-1056] [JBEAP-9934] CS tool, Without --location parameter a credential store storage file isn't saved (or save as is expected).

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1058
JBEAP: https://issues.jboss.org/browse/JBEAP-10137
This PR also resolves:
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1059
JBEAP: https://issues.jboss.org/browse/JBEAP-10139
> [ELY-1058] When we set wrong ITERATION value (too big number or string) then we get NumberFormatException.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
These changes allow creating empty credential stores. Additionally it resolves a minor problem in the value used as secret for the report summary.
Jira issues are:
https://issues.jboss.org/browse/ELY-1104
https://issues.jboss.org/browse/JBEAP-9031
> [ELY-1104][JBEAP-9031] Allow creating empty credential stores

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1054
JBEAP: https://issues.jboss.org/browse/JBEAP-10113
Empty secret value should be possible - it was resolved in the CLI already by WFCORE-2455.
> [ELY-1054] CS tool, There is possibility add EMPTY alias name and EMPTY secret value to credential store storage file through wildfly-elytron-tool.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1056 (reopen)
JBEAP: https://issues.jboss.org/browse/JBEAP-9934 (reopen)
Making the "location" option required.
> [ELY-1056] (reopen) CS tool, Without --location parameter a credential store storage file isn't saved (or save as is expected).

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1085
JBEAP: https://issues.jboss.org/browse/JBEAP-10386
"--create" option is only a flag and doesn't expect any arguments.
> [ELY-1085] CS tool, Help contains wrong description of "--create" option, there is description with true/false value.

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
If user omits the --keystore-password argument in vault command, an interactive prompt is shown to get a valid value. 
Jira issues:
https://issues.jboss.org/browse/ELY-1128
https://issues.jboss.org/browse/JBEAP-10696
> [ELY-1128][JBEAP-10696]: Show an interactive prompt when keystore-password is missing using vault command

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1124
JBEAP: https://issues.jboss.org/browse/JBEAP-10685
> [ELY-1124] WildFly Elytron Tool, Vault commands with wrongly filled path to vaults should fail.

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1164
JBEAP: https://issues.jboss.org/browse/JBEAP-10966
> [ELY-1164] Wildfly Elytron Tool, credential-store command doesn't support redirection (<, <<) when multiple options are missing which show prompts.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
Issue was re-opened because there was an inconsistence between credential store names used in the summary report.
Jira issues are:
https://issues.jboss.org/browse/ELY-1091
https://issues.jboss.org/browse/JBEAP-10411
> [ELY-1091][JBEAP-10411]: Fixed inconsistent credential store name found in the summary report

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
If user omits the --secret argument in mask command, an interactive prompt is shown to get a valid value.
Jira issues:
https://issues.jboss.org/browse/ELY-1162
https://issues.jboss.org/browse/JBEAP-10959
> ELY-1162: Show an interactive prompt when secret is missing using mask command

- src/main/java/org/wildfly/security/tool/ElytronTool.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1086
JBEAP: https://issues.jboss.org/browse/JBEAP-10395
Implementing command specific help message.
> [ELY-1086](Reopen) CS tool, Command without any option must show help rather then error message about required options.

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1205
JBEAP: https://issues.jboss.org/browse/JBEAP-11163
Adding option --debug which enables print stack trace when error occurs.
> [ELY-1205] Wildfly Elytron Tool error output would contain error message rather than stacktrace.

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
- src/test/java/org/wildfly/security/tool/VaultCommandTest.java
- src/test/resources/bulk-vault-conversion-no-alias
- src/test/resources/bulk-vault-conversion-no-enc-dir
- src/test/resources/bulk-vault-conversion-no-keystore-password
- src/test/resources/bulk-vault-conversion-no-keystore-url
- src/test/resources/bulk-vault-conversion-no-location
Issue: https://issues.jboss.org/browse/ELY-1131
> [ELY-1131] WildFly Elytron Tool, For vault command bulk-convert is missing validation for parsed values from description file

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
Aliases were removed as resources so print summary must be adapted according. to that change.
Jira issues:
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1091
JBEAP: https://issues.jboss.org/browse/JBEAP-10411
> ELY-1091: Fix print summary because aliases are not longer resources

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
- src/test/resources/bulk-vault-conversion-no-alias
- src/test/resources/bulk-vault-conversion-no-enc-dir
- src/test/resources/bulk-vault-conversion-no-keystore-password
- src/test/resources/bulk-vault-conversion-no-keystore-url
- src/test/resources/bulk-vault-conversion-no-location
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1231
JBEAP: https://issues.jboss.org/browse/JBEAP-11392
> [ELY-1231] WildFly Elytron Tool, Vault commands with --enc-dir option leads to directory which doesn't contain VAULT.dat should fail.

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1228
JBEAP: https://issues.jboss.org/browse/JBEAP-11376
> [ELY-1228] Wildfly Elytron Tool, help output contains "java -jar wildfly-elytron-tool.jar" instead of "wildfly-elytron.sh/bat/ps1" script name.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
https://issues.jboss.org/browse/JBEAP-10972
https://issues.jboss.org/browse/ELY-1165
> [ELY-1165] credential-store command "add" option doesn't contain entry-type in summary CLI command

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1303
JBEAP: https://issues.jboss.org/browse/JBEAP-12219
Added new options to "vault" command which are similar to "credential-store" command:
--type
--credential-store-provider
--other-providers
> [ELY-1303] WildFly Elytron Tool, Vault command should support set security provider to convert vaults to custom credential store implementation.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
(cherry picked from commit 3fb82201948ea25ddaae07cc7928cae6282a20d9)
https://issues.jboss.org/browse/ELY-1294 1.2.x branch
It shouldn't compute only password inside the add alias option, masked password should be present for other options as well to be displayed later in summary output.
> ELY-1294 compute password earlier to validate salt parameter length.
