- pom.xml
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/test/java/org/wildfly/security/tool/BaseToolTest.java
- src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
https://issues.jboss.org/browse/JBEAP-8996
https://issues.jboss.org/browse/WFLY-8176
There another commit fixing creation of temp file in main directory (just maven plugin configuration).
> Fix to salt NPE

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
> add new "mask" command to create MASK- strings

- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
wildfly-elytron-tool: https://issues.jboss.org/browse/WFCORE-2484
JBEAP: https://issues.jboss.org/browse/JBEAP-9038
> [WFCORE-2484] CS tool, log exception on error

- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
follow up for:
https://issues.jboss.org/browse/JBEAP-9022
> [JBEAP-9022] fix of help message to explain values of URI parameters

- src/main/java/org/wildfly/security/tool/Command.java
https://issues.jboss.org/browse/JBEAP-9902
> [JBEAP-9902] make help output format wide enough

- pom.xml
- src/test/java/org/wildfly/security/tool/AbstractCommandTest.java
- src/test/java/org/wildfly/security/tool/CredentialStoreCommandInputTest.java
- src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
- src/test/java/org/wildfly/security/tool/MaskCommandTest.java
Add various tests for wildfly-elytron-tool
> Add various tests for wildfly-elytron-tool

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1057
JBEAP: https://issues.jboss.org/browse/JBEAP-10126
> [ELY-1057] [JBEAP-10126] CS tool, There isn't any error message when I want to mask password and omit salt.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
https://issues.jboss.org/browse/ELY-1089
> [ELY-1089] CS tool, missing parameters compared to management API

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
- src/test/java/org/wildfly/security/tool/AbstractCommandTest.java
- src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
- src/test/java/org/wildfly/security/tool/VaultCommandTest.java
https://issues.jboss.org/browse/WFCORE-2427
https://issues.jboss.org/browse/JBEAP-6907
> [WFCORE-2427] get rid of uri option to be consistent with subsystem

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1088
JBEAP: https://issues.jboss.org/browse/JBEAP-10397
> [ELY-1088] CS tool, Redirection (<, <<) do not work in wildfly-elytron-tool

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
Issue: [ELY-1084](https://issues.jboss.org/browse/ELY-1084)
Downstream: [JBEAP-10383](https://issues.jboss.org/browse/JBEAP-10383)
----
Also added a new message for when the store has no aliases
> ELY-1084: show error when removing non-existent alias

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1091
JBEAP: https://issues.jboss.org/browse/BEAP-10411
> ELY-1091: Fixed summary output to reflect the chosen option

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
- src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
- src/test/java/org/wildfly/security/tool/MaskCommandTest.java
https://issues.jboss.org/browse/JBEAP-9905
plus one more fix to help header messages
> CS tool, Usage of --help option with other options must display help rather than error message

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
Jira issues:
https://issues.jboss.org/browse/ELY-1107
https://issues.jboss.org/browse/JBEAP-10592
> [ELY-1107][JBEAP-10592]: removed attribute duplicity on summary report

- src/main/java/org/wildfly/security/tool/ElytronTool.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1086
JBEAP: https://issues.jboss.org/browse/JBEAP-10395
> [ELY-1086] CS tool, Command without any option must show help rather then error message about required options.

- src/main/java/org/wildfly/security/tool/Command.java
- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
- src/test/java/org/wildfly/security/tool/CredentialStoreCommandTest.java
- src/test/java/org/wildfly/security/tool/MaskCommandTest.java
- src/test/java/org/wildfly/security/tool/VaultCommandTest.java
Issue: https://issues.jboss.org/browse/ELY-1036
> [ELY-1036] There is possibility define same option parameter more times

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1129
JBEAP: https://issues.jboss.org/browse/JBEAP-10702
> [ELY-1129] WildFly Elytron Tool, Vault command bulk-convert must have better description in --help output.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1122
JBEAP: https://issues.jboss.org/browse/JBEAP-10680
> [ELY-1122] WildFly Elytron Tool, Vault Command --bulk-convert ignore --summary option.

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1145
JBEAP: https://issues.jboss.org/browse/JBEAP-10808
> [ELY-1145] WildFly Elytron Tool, Vault command bulk-convert must contain in --help output which options are required.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1092
JBEAP: https://issues.jboss.org/browse/JBEAP-10430
> [ELY-1092] CS tool, There is success message when we try to list aliases from non-existent storage file.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
https://issues.jboss.org/browse/ELY-1167
https://issues.jboss.org/browse/JBEAP-10801
> [ELY-1167] Load custom credential store implementation and other provider using service loader

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1123
JBEAP: https://issues.jboss.org/browse/JBEAP-10681
> [ELY-1123] WildFly Elytron Tool, Vault command: converted storage file overwrites existing file on filesystem.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1093
JBEAP: https://issues.jboss.org/browse/JBEAP-10431
This PR also resolves issue JBEAP-10430
> [ELY-1093] CS tool, When we try to find out if alias exists in non-existent credential store storage file then we get success message.

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronTool.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
wildfly-elytron-tool: https://issues.jboss.org/browse/ELY-1205
JBEAP: https://issues.jboss.org/browse/JBEAP-11163
> [ELY-1205](Reopen) Wildfly Elytron Tool, Wildfly Elytron Tool error output would contain error message rather than stacktrace.

- src/main/java/org/wildfly/security/tool/VaultCommand.java
https://issues.jboss.org/browse/WFCORE-3001
https://issues.jboss.org/browse/JBEAP-11740
> [WFCORE-3001] Ensure the vault command outputs the correct credential store file when the location is specified as an implementation property

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
- src/main/java/org/wildfly/security/tool/MaskCommand.java
- src/main/java/org/wildfly/security/tool/VaultCommand.java
https://issues.jboss.org/browse/JBEAP-11786
> Masked Password related changes

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
https://issues.jboss.org/browse/ELY-1294
https://issues.jboss.org/browse/JBEAP-12239
> [ELY-1294] allow to validate parameters without --summary.

- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
https://issues.jboss.org/browse/ELY-1127
https://issues.jboss.org/browse/JBEAP-10695
> [ELY-1127] add default values to vault command options description

- src/main/java/org/wildfly/security/tool/CredentialStoreCommand.java
- src/main/java/org/wildfly/security/tool/ElytronToolMessages.java
(7.1.x) https://issues.jboss.org/browse/JBEAP-14702
Upstream: https://issues.jboss.org/browse/ELY-1576 (PR: #137)
> [ELY-1576] Wildfly Elytron Tool, location is required even for non-filebased type e.g. PKCS11

- pom.xml
https://issues.jboss.org/browse/ELY-1567
Make the JAR Multi-Release
1.2.x branch PR (cherry-pick from https://github.com/wildfly-security/wildfly-elytron-tool/pull/144)
> [ELY-1567] Make the JAR Multi-Release

- README.md
https://issues.redhat.com/browse/ELY-2220?filter=12364234
> Update wildfly-elytron-tool/README to indicate that this repo is no longer used revised
